name: test
on:
#  schedule:
#    - cron:  '35 12 * * *'
  push:
#  pull_request:
    branches:
      - main
#    paths:
#      - "src/**"
#      - "!*.md"
  workflow_dispatch:
    inputs:
      target_env:
        type: choice
        required: true
        options:
          - "dev"
          - "stg"

jobs:
  set-env:
    name: set-env
    runs-on: ubuntu-latest
    outputs:
      stage: ${{ steps.setenv.outputs.stage}}
    steps:
      - name: set env
        id: setenv
        run: | 
          #if [ -n "${{ github.event.inputs.target_env }}" ]; then 
          #  obj = `jq -c -n '{include: [{ env: "${{ github.event.inputs.target_env }}" }]}'`
          #  echo "stage=${obj}"  
          #  echo "stage=${obj}" >> $GITHUB_OUTPUT 
          #else 
            #obj=$(jq -c -n '{include: [{ env: "dev" },{ env: "stg" }]}')
            obj=$(echo '{ "env" : "dev" }' | jq -c)
            echo "stage=${obj}"              
            echo "stage=${obj}" >> $GITHUB_OUTPUT 
#            echo "${{ toJson($GITHUB_OUTPUT) }}"
          #fi
           
  env-check:
    needs: set-env
#    strategy:
#      matrix:
#        stage: ${{ fromJson(needs.set-env.outputs.stage) }}
    env: 
#      env_name: ${{ matrix.stage.env}}
      env_name: ${{ fromJson(needs.set-env.outputs.stage) }}
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "env.env_name ${{ env.env_name }}"
#          echo "env.env_name ${{ needs.set-env.outputs.stage }}"
#          echo "stage ${{ needs.set-env.outputs.stage }}"

#  test1:
#    name: check-ut
#    runs-on: ubuntu-latest
#    steps:
#      - name: checkout repo
#        uses: actions/checkout@v4
#
#  test2:
#    name: check-it
#    runs-on: ubuntu-latest
#    steps:
#      - name: checkout repo
#        uses: actions/checkout@v4
#      
##      - name: failure
##        run: exit 1
#      
#  merge-check:
#    name: mergecheck
#    needs: [test1, test2]
##    if: success() 
#    runs-on: ubuntu-latest
#    steps:
##      - name: checkout repo
##        uses: actions/checkout@v4
#      
#      - name: echo
#        run: echo "merge can be done"
      