name: test
on:
  schedule:
    - cron:  '*/1 * * * 1-6'
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "!*.md"


jobs:
  test:
    name: check-ut
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      
      - name: failure
        run: exit 1
