name: test
on:
#  schedule:
#    - cron:  '35 12 * * *'
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "!*.md"


jobs:
  test1:
    name: check-ut
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      
  test2:
    name: check-it
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      
      - name: failure
        run: exit 1
      
  merge-check:
    name: merge-check
    needs: [test1, test2]
    if: success() 
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      
      - name: merge-check
        run: echo "merge can be done"
      